# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [8]:
print(np.__version__)
np.__config__.show()

1.16.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10

In [4]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array

In [7]:
print("%d bytes"% (arr.size * arr.itemsize))

80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [20]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [22]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [24]:
vec = np.arange(10,50)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last)

In [26]:
vec[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [28]:
a = np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [29]:
nonze = np.nonzero([1,2,0,0,4,0])
nonze

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [35]:
np.random.random((3,3,3))

array([[[0.07328623, 0.38002825, 0.73350989],
        [0.38843623, 0.36061338, 0.19951856],
        [0.11543206, 0.56948253, 0.26245589]],

       [[0.7487469 , 0.87684232, 0.57804491],
        [0.96389202, 0.20105355, 0.72337131],
        [0.71206837, 0.58034962, 0.97552229]],

       [[0.49485153, 0.84905457, 0.46803754],
        [0.56285637, 0.86569126, 0.82520665],
        [0.37996958, 0.8315451 , 0.32742309]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [39]:
b = np.random.random((10,10))
print(b.max())
print(b.min())

0.9908946909538193
0.0022836924017461957


#### 14. Create a random vector of size 30 and find the mean value

In [46]:
v = np.random.random(30)
print(v)
print("mean : ",v.mean())

[0.70965272 0.2804606  0.79743879 0.67956003 0.47203066 0.34806137
 0.20598861 0.18005136 0.32102067 0.40852136 0.3646999  0.11990002
 0.75306882 0.93914733 0.43636615 0.80578465 0.22880614 0.66380666
 0.53782515 0.86480386 0.34546036 0.98987602 0.57663664 0.85037911
 0.11759228 0.76192776 0.66803933 0.64803303 0.80796139 0.82548094]
mean :  0.5569460574250421


#### 15. Create a 2d array with 1 on the border and 0 inside

In [47]:
c = np.ones((5,5))
c[1:-1,1:-1] = 0
c

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [52]:
ar = np.ones((3,3))
np.pad(ar,pad_width = 1,mode = 'constant',constant_values = 0)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [53]:
0 * np.nan

nan

In [54]:
np.nan == np.nan

False

In [55]:
np.inf > np.nan

False

In [56]:
np.nan - np.nan

nan

In [57]:
np.nan in set([np.nan])

True

In [58]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [59]:
di = np.diag(1+np.arange(4),k=-1)
di

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [61]:
chess = np.zeros((8,8))
chess[1::2,::2] = 1
chess[::2,1::2] = 1
chess

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [63]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)